### PR TITLE
Replace com.twilio with dev.guardrail

### PR DESCRIPTION
**Pull request by nickhudkins**
✨ It's so shiny

### CODE REVIEW

**Comment by kelnos** [comment]
I think this would also be a good time to remove the `_2.12` suffix on the artifact ID.  It's never been needed, but I've left it to avoid pain for end-users.  Would you mind taking care of that in this PR as well?

**Comment by nickhudkins** [comment]
Sure can!

**Review by kelnos — APPROVED** [review]
excellent, thank you!

**Comment by kelnos** [comment]
@blast-hardcheese since it's not all that feasible to do a legacy org check on the maven plugin, do you want to do a 1.0.0 publish on the old org before we merge this, with some WARN output that notifies of the org change?

**Comment by kelnos** [comment]
Strange, I've not seen this error before:

```
Error:  Failed to execute goal dev.guardrail:guardrail-maven-plugin:d71de7b-SNAPSHOT:generate-sources (generate-petstore-spring-mvc-server) on project codegen-spring-mvc-java: Execution generate-petstore-spring-mvc-server of goal dev.guardrail:guardrail-maven-plugin:d71de7b-SNAPSHOT:generate-sources failed: A required class was missing while executing dev.guardrail:guardrail-maven-plugin:d71de7b-SNAPSHOT:generate-sources: scala/compat/java8/OptionConverters$RichOptionalGeneric$
```

**Comment by blast-hardcheese** [comment]
> it's not all that feasible to do a legacy org check on the maven plugin

It turns out [maven supports this natively](https://maven.apache.org/guides/mini/guide-relocation.html)!

Considering we're already releasing dev.guardrail stuff using the old versioning scheme, I think we should merge this and release it as 0.64.4 as well, to maintain parity with the first dev.guardrail artifact(s) in maven central.

I also asked a question in gitter which may slightly delay the discussion on hitting the 1.0 release, mainly about using this as an opportunity to clarify our versioning strategy more broadly. I'd like to make sure it doesn't turn into a nightmare from a consumer usability standpoint, but from my current thinking it has quite a bit of advantages for users.

**Comment by kelnos** [comment]
Oh, neat, didn't know that.  I hope maven is loud about using relocation info so it will actually warn users that things have changed.

**Comment by blast-hardcheese** [comment]
Closing this as it required more manual intervention to do the migration and I forgot to circle back here. Thank you for your help both here and in the other repos!

**Pull request closed without merging**
